# Spring properties
spring:
  application:
    name: hotel-service  # Identify this application
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker hotel-server.templates
  thymeleaf:
    cache: false       # Allow Thymeleaf hotel-server.templates to be reloaded at runtime
    prefix: classpath:/hotel-server/hotel-server.templates/    # Trailing / mandatory
                       # Template location for this application only

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# HTTP Server
server:
  port: 3334   # HTTP (Tomcat) port

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly


eureka:
#  client:
#      registerWithEureka: true
#      fetchRegistry: true
#      serviceUrl:
#        defaultZone: http://Travalo:xxqi1nkv@localhost:1111/eureka/
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://Travalo:xxqi1nkv@localhost:1111/eureka/

  instance:
    instance:
      leaseRenewalIntervalInSeconds: 10
      statusPageUrlPath: /diagnostics/admin/info
      healthCheckUrlPath: /diagnostics/admin/health
      metadataMap:
        password: password
  #  leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}




